---
- block:
  # block for 'become: true'

    - name: Remove primary zone files
      file:
        path: /etc/named/primaries
        state: absent
      when: keep_primary_zones is not defined or not keep_primary_zones

    - name: Stop service
      service:
        name: named-chroot
        state: stopped
      tags:
        - service_state
      when: state == 'absent' or state == 'present'
    
    - name: Remove bind
      yum:
        name: '{{ item }}'
        state: absent
      with_items:
        - '{{ bind_packages }}'
      tags:
        - packages
      when: state == 'absent'
    
    - block:
      # block for 'state != "absent"'  

        - name: Ensure required packages are installed
          yum:
            name: '{{ item }}'
            state: present
          with_items:
            - '{{ bind_packages }}'
          notify:
            - restart named-chroot
          tags:
            - packages
            - setup
    
        - name: Ensure existence of slaves and primaries directories
          file:
            path: '{{ bind_dir }}'
            state: directory
            owner: named
            group: named
            mode: 0770
          notify:
            - restart named-chroot
          with_items:
            - /etc/named/slaves
            - /etc/named/primaries
          loop_control:
            loop_var: bind_dir
          tags:
            - setup

        - name: Render named config file
          template:
            src: named.conf.j2
            dest: /etc/named.conf
            mode: 0640
            owner: root
            group: named
          notify:
            - restart named-chroot
          tags:
            - config

        - name: Copy local zone files
          copy:
            src: '{{ local_zone_file_dir }}'
            dest: /etc/named/primaries
            owner: named
            group: named
            mode: 0600
            directory_mode: 0700
          notify:
            - restart named-chroot
          tags:
            - config
            - primary_zones
            - copy_local_primary_zones
            - copy_primary_zones
          when: local_zone_file_dir is defined

        - block:
            - name: Copy remote zone files
              shell: cp -r * /etc/named/primaries/
              args:
                chdir: '{{ remote_zone_file_dir }}'
              notify:
                - restart named-chroot
            - name: Fix file permissions
              file:
                path: /etc/named/primaries
                state: directory
                owner: named
                group: named
                mode: 0600
              notify:
                - restart named-chroot
            - name: Fix directory permissions
              file:
                path: /etc/named/primaries
                mode: 0700
          tags:
            - config
            - primary_zones
            - copy_remote_primary_zones
            - copy_primary_zones
          when: remote_zone_file_dir is defined

        - name: Collect list of primary zones
          find:
            paths: /etc/named/primaries
            patterns: 'db.*'
            file_type: file
          register: primary_zones
          tags:
            - config
            - primary_zones

        - name: Render master zone config
          template:
            src: 'named.primary_zones.j2'
            dest: '/etc/named/named.primary_zones'
            mode: 0640
            owner: root
            group: named
          notify:
            - restart named-chroot
          tags:
            - config
            - primary_zones
       
        - name: Report facts
          set_fact:
             primary_zones: '{{ primary_zones.files|map(attribute="path")|list|map("replace", "/etc/named/primaries/db.", "")|list }}'

        - name: Render slave zone config
          template:
            src: 'named.secondary_zones.j2'
            dest: '/etc/named/named.secondary_zones'
            mode: 0640
            owner: root
            group: named
          notify:
            - restart named-chroot
          tags:
            - config

        - name: Control named service
          service:
            name: named-chroot
            state: '{{ state }}'
          tags:
            - service_state

      when: state != 'absent'

  become: true
  become_user: root
