---
- block:

  - name: Stop service
    service:
      name: named-chroot
      state: stopped
    when: state == 'absent' or state == 'present'
  
  - name: Remove bind
    yum:
      name: '{{ item }}'
      state: absent
    with_items:
      - '{{ bind_packages }}'
    when: state == 'absent'
  
  - block:
    - name: Ensure required packages are installed
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - '{{ bind_packages }}'
      notify:
        - restart named-chroot
  
    - name: Ensure existence of slaves and primaries directories
      file:
        path: '{{ bind_dir }}'
        state: directory
        owner: named
        group: named
        mode: 0770
      notify:
        - restart named-chroot
      with_items:
        - /etc/named/slaves
        - /etc/named/primaries
      loop_control:
        loop_var: bind_dir

    - name: Render named config file
      template:
        src: named.conf.j2
        dest: /etc/named.conf
        mode: 0640
        owner: root
        group: named
      notify:
        - restart named-chroot

    - name: Render master zone config
      template:
        src: 'named.primary_zones.j2'
        dest: '/etc/named/named.primary_zones'
        mode: 0640
        owner: root
        group: named
      notify:
        - restart named-chroot

    - name: Render slave zone config
      template:
        src: 'named.secondary_zones.j2'
        dest: '/etc/named/named.secondary_zones'
        mode: 0640
        owner: root
        group: named
      notify:
        - restart named-chroot

    - name: Control named service
      service:
        name: named-chroot
        state: '{{ state }}'

    when: state != 'absent'

  become: true
  become_user: root
