---
- block:

  - name: Stat config file
    stat:
      path: /etc/named.conf
    register: st
  
  - name: Stop service
    service:
      name: named-chroot
      state: stopped
    when: state == 'absent' or state == 'present'
  
  - name: Remove bind
    yum:
      name: '{{ item }}'
      state: absent
    with_items:
      - '{{ bind_packages }}'
    when: state == 'absent'
  
  - block:
    - name: Ensure required packages are installed
      yum:
        name: '{{ item }}'
        state: present
      with_items:
          - '{{ bind_packages }}'
  
    # right after package installation, put our default config there.
    - name: Render default config file
      template:
        src: named.conf.default.j2
        dest: /etc/named.conf
        mode: 0640
        owner: root
        group: named
      when: not st.stat.exists
    - name: make sure the include files exist
      template:
        src: '{{item}}.j2'
        dest: '/etc/named/{{item}}'
        mode: 0640
        owner: root
        group: named
      with_items:
        - named.primary_zones
        - named.secondary_zones
      when: not st.stat.exists

    - name: Ensure existence of slaves and primaries directories
      file:
        path: '{{ bind_dir }}'
        state: directory
        owner: named
        group: named
        mode: 0770
      with_items:
        - /etc/named/slaves
        - /etc/named/primaries
      loop_control:
        loop_var: bind_dir

    - name: Render config settings
      include_tasks: tasks_render_config.yml
  
    - name: Control named service
      service:
        name: named-chroot
        state: '{{ state }}'

    when: state != 'absent'

  become: true
  become_user: root
