---
- name: Converge
  hosts: all
  tasks:
    - copy:
        src: remote_zones/
        dest: /tmp/zones/
    - file:
        path: /etc/named/primaries/canary
        state: touch
    - include_role:
        name: tinx.bind
      vars:
        recursion: true
        allow_query:
          - 127.0.0.1
          - 10.40.0.0/24
          - 10.50.0.0/24
          - 10.60.0.0/24
        allow_recursion:
          - 127.0.0.1
          - 10.40.0.0/24
          - 10.50.0.0/24
          - 10.60.0.0/24
        allow_transfer:
          - 10.40.0.5
          - 10.40.0.4
        listen_on:
          - port: 53
            interfaces:
              - 127.0.0.1
              - 10.40.0.6
        listen_on_v6:
          - port: 10053
            interfaces:
              - 0.0.0.0
        slave_zones:
          - name: etcd.openshift.uf0.de
            masters:
              - 10.40.0.5
              - 10.40.0.4
          - name: node.openshift.uf0.de
            masters:
              - 10.40.0.5
              - 10.40.0.4
        local_zone_file_dir: 'zones/'
        remote_zone_file_dir: '/tmp/zones/'
        keep_primary_zones: true
    - debug:
        var: hostvars[groups.all[0]].primary_zones
