---
- name: Converge
  hosts: all
  tasks:
    - name: Create remote zone source directory
      copy:
        src: remote_zones/
        dest: /tmp/zones/
    - name: Create conf dir in preparation for canary test
      file:
        path: /etc/named/primaries
        state: directory
    - name: Create dummy canary file to detect whether it'll be deleted
      file:
        path: /etc/named/primaries/canary
        state: touch
      changed_when: false
    - name: Include role under test
      include_role:
        name: tinx.bind
      vars:
        recursion: true
        allow_query:
          - 127.0.0.1
          - 10.40.0.0/24
          - 10.50.0.0/24
          - 10.60.0.0/24
        allow_recursion:
          - 127.0.0.1
          - 10.40.0.0/24
          - 10.50.0.0/24
          - 10.60.0.0/24
        allow_transfer:
          - 10.40.0.5
          - 10.40.0.4
        allow_notify:
          - 10.40.0.5
          - 10.40.0.4
        also_notify:
          - 10.40.0.6
        listen_on:
          - port: 53
            interfaces:
              - 127.0.0.1
              - 10.40.0.6
        listen_on_v6:
          - port: 10053
            interfaces:
              - '::'
        slave_zones:
          - name: mordor.example.com
            masters:
              - 10.40.0.5
              - 10.40.0.4
          - name: shire.example.com
            masters:
              - 10.40.0.5
              - 10.40.0.4
        slave_zone_list:
          - rivendell.example.com
          - rohan.example.com
        master_servers:
          - 10.70.0.4
          - 10.70.0.5
        local_zone_file_dir: 'zones/'
        remote_zone_file_dir: '/tmp/zones/'
        keep_primary_zones: true
#    - debug:
#        var: hostvars[groups.all[0]].primary_zones
